### ISSUE TITLE
Hi Magdalena ! A bug on R λαχ-σ, no edition possible anymore. Help, please !

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#309]
Many thanks for Theudagoras.
Many thanks in advance for this one.
With best wishes,
Sophie

**Comment by tuurma** [comment]
the cause of trouble was extra space at the end of λαχ-σ morpheme identifier, I have fixed that on the server but need to think about preventing similar problems occurring again

**Comment by Hippodamie** [comment]
Many thanks, Magdalena. I’lle be aware and will tell them.
Best wishes,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

 Sorry to have answered too quickly, but actually, it still does not work: I cannot open the sub-window for the names Apolexis, Antilexis, noways neither for Anti, nor for lex/lax. And there does not appear any root anymor in the colum R2 !!!

Could you please help?
Good night.
With best wishes,
Sophie

**Comment by tuurma** [comment]
It was same thing - roots used there had extra space after them. I think I fixed the ones you mentioned, but if problem surfaces on some other name try to edit 'root' field and delete the space.

**Comment by Hippodamie** [comment]
Dear Magdalena,

Many thanks for your work on λαχ-σ. 
We are often 3 people working at the same time and could be more. We have less than 3000 names edited… And loading is most often very, very slow … thus timeconsuming, what is a pity since time is money (!) especially for one of us, but actually for everyone.

Another (bad) point is  that a very big wifi access is necessary to load, which means that in academic places like when I teach, in the libraries and when I would like to present LGPN-Ling in a conference or seminary, there are so many people using wifi that I never can load, except when I work at home.

How to manage for us to be able to work in better conditions?
Thanks in advance for your answer.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
Closing as this seems fixed long time ago
